site_name: lernOS für Dich Leitfaden

docs_dir: src

site_dir: ../docs/de

nav:
    - Über lernOS: index.md
    - Grundlagen:
        - Grundlagen: 1-0-Grundlagen.md
        - Wissensgesellschaft und Wissensarbeit: 1-1-Wissensgesellschaft-und-Wissensarbeit.md
        - Persönliche Wissens- und Lernumgebung: 1-2-Persoenliche-Wissens-und-Lernumgebungen.md
        - Lebenslanges Lernen mit lernOS: 1-3-Lebenslanges-Lernen-mit-lernOS.md
    - Lernpfade:
        - Lernpfade: 2-0-Lernpfade.md
        - WOL Lernpfad:
            - WOL Lernpfad: 2-1-0-Lernpfad-WOL.md
            - Lege dein Ziel für die nächsten 12 Wochen fest (Kata): 2-1-1-Kata-1.md
            - Wer kann dir bei deinem Ziel helfen? (Kata): 2-1-2-Kata-2.md
            - Teile etwas im Netzwerk (Kata): 2-1-3-Kata-3.md
            - Mache Termine mit dir selbst (Kata): 2-1-4-Kata-4.md
            - Egosurfe dich! (Kata): 2-1-5-Kata-5.md
            - Beschreibe dich mit 25 Tags (Kata): 2-1-6-Kata-6.md
            - Aktualisiere deinen digitalen Zwilling (Kata): 2-1-7-Kata-7.md
            - Poste deine Top 10 Trüffel (Kata): 2-1-8-Kata-8.md
            - Welche Kanäle willst du nutzen? (Kata): 2-1-9-Kata-9.md
            - Welche Communities können dir helfen? (Kata): 2-1-10-Kata-10.md
            - Schreibe einen Brief an dein zukünftiges Ich (Kata): 2-1-11-Kata-11.md
        - OKR Lernpfad:
            - OKR Lernpfad: 2-2-0-Lernpfad-OKR.md
            - Top 10 Quellen zu OKRs (Kata): 2-2-1-Kata-1.md
            - Richte deine OKR-Umgebung ein (Kata): 2-2-2-Kata-2.md
            - Definiere OKRs für deinen Sprint (Kata): 2-2-3-Kata-3.md
            - Finalisiere deine OKRs für den Sprint (Kata): 2-2-4-Kata-4.md
            - Führe dein Weekly Check-In durch (Kata): 2-2-5-Kata-5.md
            - Tools für OKRs (Kata): 2-2-6-Kata-6.md
            - Scoring vs. Measuring Key Results (Kata): 2-2-7-Kata-7.md
            - Stretch Goals and Moonshots (Kata): 2-2-8-Kata-8.md
            - What is your Confidence Level? (Kata): 2-2-9-Kata-9.md
            - Individual vs. Team/Organizational OKRs (Kata): 2-2-10-Kata-10.md
            - OKR Review (Kata): 2-2-11-Kata-11.md
        - GTD Lernpfad:
            - GTD Lernpfad: 2-3-0-Lernpfad-GTD.md
            - Mach Dich mit den Grundlagen vertraut (Kata): 2-3-1-Kata-1.md
            - Sammeln - Mind-Sweep (Kata): 2-3-2-Kata-2.md
            - Verarbeiten - Die 2 Minuten Regel (Kata): 2-3-3-Kata-3.md
            - Organisieren - Listen & Kontexte aufbauen (Kata): 2-3-4-Kata-4.md
            - Durchsehen - Der Wochenrückblick (Kata): 2-3-5-Kata-5.md
            - Erledigen (Kata): 2-3-6-Kata-6.md
            - Projekte - Werdet wie die Kinder (Kata): 2-3-7-Kata-7.md
            - Arbeite die 5 Phasen durch (Kata): 2-3-8-Kata-8.md
            - Die Macht des nächsten Schritts (Kata): 2-3-9-Kata-9.md
            - Das 6-Horizonte-Modell (Kata): 2-3-10-Kata-10.md
            - Kontinuierliche Verbesserung - Der Weg zur Meisterschaft (Kata): 2-3-11-Kata-11.md
    - Anhang: 3-Anhang.md

theme:
    name: 'material'
    palette:
        primary: 'deep orange'
        accent: 'deep orange'
    language: de

repo_name: 'cogneon/lernos-for-you'
repo_url: 'https://github.com/cogneon/lernos-for-you'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/lern_os
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/showcase/lern-os
        - icon: fontawesome/brands/github
          link: https://github.com/cogneon
    disqus: lernos